fix(gke-cluster): update gke-cluster config
demeter-run/up pull request #164
Opened 2024-11-22 01:54 UTC by verbotenj

2024-12-20 00:30 UTC, wolf31o2 requested changes

2024-12-20 00:30 UTC, wolf31o2 commented on common/defaults-gcp.yaml
>        demeter.run/compute-profile: general-purpose
The sla/profile here doesn't match the taints below.

2024-12-20 00:30 UTC, wolf31o2 commented on common/defaults-gcp.yaml
>        demeter.run/compute-profile: general-purpose
It's best-effort and general-purpose here, but consistent and disk-intensive below.

2024-12-20 00:30 UTC, wolf31o2 commented on modules/common/cert-manager/stage2/main.tf
> +    value = "consistent"
Why are we changing these?

2024-12-20 00:30 UTC, wolf31o2 commented on stage2/main.tf
> +  storage_class = "hyperdisk-balanced"
This needs to be `gp` on AWS and k3d.

2024-12-20 00:30 UTC, wolf31o2 commented on stage3/kupo.tf
> +        storage_class_name = "hyperdisk-balanced-immediate"
This needs to be configurable.

2024-12-20 00:30 UTC, wolf31o2 commented on stage3/nodes.tf
> +  source                          = "git::https://github.com/blinklabs-io/demeter-ext-cardano-node.git//bootstrap?ref=feat/list-tolerations"
This can be switched back to upstream.

2024-12-20 00:30 UTC, wolf31o2 commented on stage3/nodes.tf
> +    #       "memory" = "4Gi"
24Gi is what I use with our helm chart.

2024-12-20 00:30 UTC, wolf31o2 commented on stage3/nodes.tf
> +    #   storage_class_name = "pd-ssd"
This will need to be configurable when we uncomment.

2024-12-20 00:30 UTC, wolf31o2 commented on stage3/nodes.tf
> +      storage_class_name = "hyperdisk-balanced"
Make this configurable

2024-12-21 16:10 UTC, verbotenj commented on modules/common/cert-manager/stage2/main.tf
> +    value = "consistent"
We shouldn't it was temporarily.

2024-12-21 21:08 UTC, wolf31o2 requested changes

2024-12-21 21:08 UTC, wolf31o2 commented on common/defaults-gcp.yaml
> +  - name: be-di-x86-az2
Also consistent

2024-12-21 23:41 UTC, wolf31o2 approved these changes

2024-12-21 23:42 UTC, merged